[package]
name = "nse_options"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
chrono = "0.4.38"
reqwest = { version = "0.11.27", features = ["json"] }
tokio = { version = "1.37.0", features = ["full"] }
