name: Bank Nifty Options Filter
description: |
  This workflow filters Bank Nifty options from NSE.json and commits the results to the repository.
  It runs daily at 2:30 AM UTC, Monday to Friday.

on:
  schedule:
    - cron: "30 2 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  filter-options:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download and Extract NSE.json
        run: |
          curl -o NSE.json.gz https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz
          gunzip -c NSE.json.gz > NSE.json
          rm NSE.json.gz
          ls -lh NSE.json

      - name: Validate NSE.json
        run: |
          if [[ ! -s NSE.json ]]; then
            echo "NSE.json is empty or missing." >&2
            exit 1
          fi
          jq empty NSE.json || { echo "Invalid JSON in NSE.json." >&2; exit 1; }

      - name: Run filter
        run: cargo run --release

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add banknifty.json
          git commit -m "Update filtered banknifty data - $(date)"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
